name: build-release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  verify-versions:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4
      - name: verify versions
        run: |
          MCLOCKS_TAG_VER=$(echo "${GITHUB_REF_NAME}" | sed 's/^v//')
          MCLOCKS_PACKAGE_VER=$(jq -r .version < package.json)
          if [ "$MCLOCKS_TAG_VER" != "$MCLOCKS_PACKAGE_VER" ]; then
            echo "❌ MCLOCKS_TAG_VER:$MCLOCKS_TAG_VER and MCLOCKS_PACKAGE_VER:$MCLOCKS_PACKAGE_VER are wrong!"
            exit 1
          fi

  publish:
    needs: verify-versions
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"
            args: ""
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest" # for Intel based macs.
            args: "--target x86_64-apple-darwin"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install libs
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend libs
        run: |
          npm install -g pnpm
          pnpm install

      - name: display version info
        run: |
          pnpm tauri info

      - uses: tauri-apps/tauri-action@v0.5.20
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseName: "mclocks v__VERSION__"
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
