name: build-test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
    paths-ignore:
      - '**/*.md'
      - '**/.gitignore'

jobs:
  build-on-linux-ubuntu-22:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: |
          npm install -g pnpm
          pnpm install
          pnpm tauri build
