name: build-test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
    paths-ignore:
      - '**/*.md'
      - '**/.gitignore'
      - '**/dependabot.yml'

jobs:
  build-on-macOS:
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install frontend dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: display version info
        run: |
          pnpm tauri info

      - name: try to build
        run: |
          pnpm tauri build
